serve:
  hostname: 0.0.0.0
  port: 8080
  playground: true
sources:
  - name: Supergraph
    handler:
      supergraph:
        source: supergraph.graphql
        operationHeaders:
          traceparent: "{context.headers['traceparent']}"
          tracestate: "{context.headers['tracestate']}"