services:
  gateway:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    healthcheck:
      test: wget http://localhost:8080/graphql || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
    environment:
      - FORK=8
      - OTEL_TRACES_EXPORTER=none
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://otel-collector:4318"
      - OTEL_NODE_RESOURCE_DETECTORS=env,host,os
      - OTEL_SERVICE_NAME=gateway
      - OTEL_SEMCONV_STABILITY_OPT_IN=http
      - NODE_OPTIONS= --require @opentelemetry/auto-instrumentations-node/register
  gateway-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "gateway",
      "--app-port", "${EXPERIMENT_CONFIG_SIDECAR_PORT:-8080}",
      "--dapr-http-port", "3500",
      "-placement-host-address", "placement:50006",
      "--config", "/config.yaml",
      "--resources-path", "/components"
    ]
    network_mode: "service:gateway"
