services:
  gateway:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CATALOG_ENDPOINT=http://localhost:3500/v1.0/invoke/catalog/method/graphql
      - WISHLIST_ENDPOINT=http://localhost:3500/v1.0/invoke/wishlist/method/
    healthcheck:
      test: wget http://localhost:8080/graphql || exit 1
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 3s
  gateway-dapr:
    image: "daprio/daprd:edge"
    command: [
      "./daprd",
      "--app-id", "gateway",
      "--app-port", "8080",
      "--dapr-http-port", "3500",
      "-placement-host-address", "placement:50006",
      "--config", "/config.yaml",
      "--resources-path", "/components"
    ]
    network_mode: "service:gateway"
